################################################################################
# ICC2 route grid/via app option 확인 스크립트
#
# 목적:
#   남은 DRC가 M1/M2/VIA1 off-grid와 M1-M2 fat-contact에 몰려 있습니다.
#   옵션 이름과 현재 기본값을 추측하지 않고 ICC2 안에서 직접 확인합니다.
#
# 주의:
#   design block을 열지 않습니다.
#   report만 생성합니다.
################################################################################

source 7_Backend_ICC2/0_Script/00_setup/icc2_common_setup.tcl

set PROBE_DIR $PROJECT_ROOT/7_Backend_ICC2/4_Report/trials/route_grid_option_probe/99_options
file mkdir $PROBE_DIR

report_app_options route.common.* > $PROBE_DIR/route_common_all.rpt
report_app_options route.detail.* > $PROBE_DIR/route_detail_all.rpt

report_app_options *off_grid* > $PROBE_DIR/off_grid_options.rpt
report_app_options *on_grid* > $PROBE_DIR/on_grid_options.rpt
report_app_options *via* > $PROBE_DIR/via_options.rpt
report_app_options *track* > $PROBE_DIR/track_options.rpt
report_app_options *pin* > $PROBE_DIR/pin_options.rpt

set fp [open $PROBE_DIR/option_probe_notes.rpt w]
puts $fp "Route grid/via option probe"
puts $fp "Generated by probe_route_grid_options.tcl"
puts $fp "Main files:"
puts $fp "  route_common_all.rpt"
puts $fp "  route_detail_all.rpt"
puts $fp "  off_grid_options.rpt"
puts $fp "  on_grid_options.rpt"
puts $fp "  via_options.rpt"
puts $fp "  track_options.rpt"
puts $fp "  pin_options.rpt"
close $fp

exit
